// examples/angular-boilerplate/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title: string = 'Scale + Angular';
}

<main>
  <div>
    <h1 class="scl-font-variant-heading-1">{{ title }}</h1>
    <scale-button
      href="https://www.brand-design.telekom.com/scale/?path=/story/scale-for-developers-scale-and-angular--page"
      title="External link"
    >
      Open the docs
    </scale-button>
  </div>
</main>

// examples/react-boilerplate/src/App.js
import './App.css';
import { ScaleButton } from '@telekom/scale-components-react-neutral';

function App() {
  return (
    <main>
      <div className="hello">
        <h1 className="scl-font-variant-heading-1">Scale + React</h1>
        <ScaleButton
          href={'https://www.brand-design.telekom.com/scale/?path=/story/scale-for-developers-scale-and-angular--page'}
          title={'External link'}
        >
          Open the docs
        </ScaleButton>
      </div>
    </main>
  );
}

export default App;
