// examples/vue3-vite-boilerplate/src/App.vue
<template>
  <div>
    <h1 class="scl-font-variant-heading-1">Scale + Vue3 + Vite </h1>
    <scale-button
      href="https://telekom.github.io/scale/?path=/story/scale-for-developers-scale-and-angular--page"
      title="External link"
    >
      Open the docs
    </scale-button>
  </div>
</template>

<style>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}

</style>

// examples/react-boilerplate/src/App.js
import './App.css';
import { ScaleButton } from '@telekom/scale-components-react-neutral';

function App() {
  return (
    <main>
      <div className="hello">
        <h1 className="scl-font-variant-heading-1">Scale + React</h1>
        <ScaleButton
          href={'https://telekom.github.io/scale/?path=/story/scale-for-developers-scale-and-angular--page'}
          title={'External link'}
        >
          Open the docs
        </ScaleButton>
      </div>
    </main>
  );
}

export default App;
