// examples/boilerplate-react/src/App.tsx
import React from 'react';
import './App.css';

const App: React.FC = () => (
  <div className="App">
    <h1>React App</h1>
    <h3>Alert</h3>
    <scale-link variant="success">Success</scale-link>
    <h3>Button</h3>
    <scale-button variant="primary">Click!</scale-button>
    <h3>Card</h3>
    <scale-card>A title</scale-card>
  </div>
);

export default App;

// examples/boilerplate-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'boilerplate-angular';

  testValue = 10;
  testText: string = 'OK';
}

<div>
    <h1>Angular App</h1>
    <h3>Link</h3>
    <scale-link variant="success">Success</scale-link>
    <h3>Button</h3>
    <scale-button>Click!</scale-button>
    <h3>Card</h3>
    <scale-card>A title</scale-card>
    <scale-slider [(ngModel)]="testValue"></scale-slider>
    <scale-text-field name="test" ngDefaultControl [(ngModel)]="testText" label="Text"></scale-text-field>
    <p>Message: {{testText}}</p>
    <p>Value: {{testValue}}</p>
</div>
