// examples/react-boilerplate/src/App.js
import './App.css';
import { ScaleButton } from '@telekom/scale-components-react-neutral';

function App() {
  return (
    <main>
      <div className="hello">
        <h1 className="scl-font-variant-heading-1">Scale + React</h1>
        <ScaleButton
          href={'https://www.brand-design.telekom.com/scale/?path=/story/scale-for-developers-scale-and-angular--page'}
          title={'External link'}
        >
          Open the docs
        </ScaleButton>
      </div>
    </main>
  );
}

export default App;

// examples/nuxt3-boilerplate/app.vue
<template>
  <div style="display:flex; flex-direction: column; width: 100%; height: 100vh; justify-content: center; align-items: center; ">
      <h1>Scale + Nuxt 3</h1>
      <scale-button
        href="https://www.brand-design.telekom.com/en/account/login/?redirect_url=/scale/"
        >Open the docs</scale-button
      >
  </div>
</template>
<style>
@import "@telekom/scale-components-neutral/dist/scale-components/scale-components.css";
</style>
